use_frameworks!

platform :ios, '12.0'

target 'GavinAudiorecorder_Example' do
  pod 'GavinAudiorecorder', :path => '../'

  target 'GavinAudiorecorder_Tests' do
    inherit! :search_paths

    
  end
end
